### ISSUE TITLE
ImportError: cannot import name signal when testing

### ISSUE THREAD

**Issue by mmakarios** [FollonSaxBass/python-telegram-bot-GAE#1]
When I try to test the application with `dev_appserver.py app.yaml` and go to `http://localhost:8080/set_webhook` in my browser, I get the following error:

```
ERROR    2017-03-26 14:23:38,333 webapp2.py:1552] import_string() failed for 'handlers.hook_handler.WebHookHandler'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Original exception:

ImportError: cannot import name signal

Debugged import:

- 'handlers' found in '/Users/Michel/Documents/ESTUDOS/python-telegram-bot-GAE/handlers/__init__.pyc'.
- 'handlers.hook_handler' not found.
Traceback (most recent call last):
  File "/Users/Michel/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/Michel/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/Michel/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1272, in default_dispatcher
    self.handlers[handler] = handler = import_string(handler)
  File "/Users/Michel/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1850, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
  File "/Users/Michel/Documents/ESTUDOS/python-telegram-bot-GAE/handlers/hook_handler.py", line 6, in <module>
    from message_handler import bot, setup, webhook
  File "/Users/Michel/Documents/ESTUDOS/python-telegram-bot-GAE/message_handler.py", line 16, in <module>
    from telegram.ext import Dispatcher, CommandHandler, MessageHandler, Filters
  File "/Users/Michel/Documents/ESTUDOS/python-telegram-bot-GAE/lib/telegram/ext/__init__.py", line 23, in <module>
    from .updater import Updater
  File "/Users/Michel/Documents/ESTUDOS/python-telegram-bot-GAE/lib/telegram/ext/updater.py", line 28, in <module>
    from signal import signal, SIGINT, SIGTERM, SIGABRT
ImportStringError: import_string() failed for 'handlers.hook_handler.WebHookHandler'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Original exception:

ImportError: cannot import name signal

Debugged import:

- 'handlers' found in '/Users/Michel/Documents/ESTUDOS/python-telegram-bot-GAE/handlers/__init__.pyc'.
- 'handlers.hook_handler' not found.
```

Is it possible to test the application? If not, why?

**Comment by martijnvdbrug** [comment]
I am having the same problem, but the problem seems to be with the updater.py from the module python-telegram-bot, not the python-telegram-bot-GAE project

**Comment by SehgalDivij** [comment]
I agree with @martijnvdbrug
